name: "Run Regression Testing Oranum"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron: '0 23 * * 5'
  
jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: CodeceptJs BDD DH Oranum Tests Checkout
        uses: actions/checkout@v2
    
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install
        
      - name: Setup Node.js Environment
        uses: microsoft/playwright-github-action@v1

      - name: Run All Tests
        run: |
          npx codeceptjs run --features --steps